### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by greenled** [greenled/portainer-stack-utils#9]
The project should have releases (like v0.1, v1.2, v2-alpha, etc.). This would allow a cleaner development flow and a clearer usage, so everybody knows about major features additions, deprecations and breaking changes. This would be particularly useful for the Docker images.

Semantic versioning should work fine.

**Comment by somq** [comment]
Hi @greenled, could you add this one please.
We would like to use your docker container as a base image but we need to identify the version of portainer-stack-utils in case things gets broken.

I guess you already know how to do it but as a quick reminder this is something like this:

```sh
git tag 0.1.0
git push --tags
docker build -t greenled/portainer-stack-utils:0.1.0-t greenled/portainer-stack-utils:latest .
docker push greenled/portainer-stack-util
```
-

**Comment by greenled** [comment]
Hi @somq. I'm glad to hear you want to build something on top of this project. I added the first release (0.1.0) and a changelog, but I am having some troubles with Docker Hub access these days. Hopefully I will solve them in the next days.

**Comment by greenled** [comment]
@somq please check the new tags at Docker Hub:

`latest`, `0.1.0` -> `0.1.0`
`dev` -> `master`

**Comment by somq** [comment]
Looks good to me, thanks!

**Comment by greenled** [comment]
Ok. I'm closing this one then.

**Comment by greenled** [comment]
There should exist some documentation about the Docker tags
